version: "3.8"
services:
  app:
    image: php:8.0-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: bash -c "composer install && php artisan serve --host=0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: your_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
